# Generated by Django 4.2.6 on 2023-10-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereading', '0004_ereading_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ereading',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ereading',
            name='state',
            field=models.IntegerField(choices=[(0, 'Checked by admin'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
