# Generated by Django 4.2.6 on 2023-10-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_reply_user_remove_topic_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Post',
        ),
    ]
