# Generated by Django 4.2.6 on 2023-10-29 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_topic_reply_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 10, 59, 13, 648688, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 10, 59, 13, 648688, tzinfo=datetime.timezone.utc)),
        ),
    ]
