# Generated by Django 4.2.4 on 2023-10-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='konten_catatan',
            new_name='isi_catatan',
        ),
    ]
