# Generated by Django 4.2.4 on 2023-10-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='buku',
        ),
    ]
