# Generated by Django 4.2.4 on 2023-10-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
