# Generated by Django 4.2.4 on 2023-10-28 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_page', '0004_remove_komen_parent'),
        ('notes', '0006_delete_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('judul_catatan', models.CharField(max_length=30)),
                ('judul_buku', models.CharField(max_length=255)),
                ('isi_catatan', models.TextField()),
                ('penanda', models.TextField()),
                ('buku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_page.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
