# Generated by Django 4.2.4 on 2023-10-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
