# Generated by Django 4.2.4 on 2023-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='penanda',
            field=models.CharField(max_length=30),
        ),
    ]
