# Generated by Django 4.2.6 on 2023-10-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_page', '0004_remove_komen_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_url', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', '😊'), ('sad', '😢'), ('neutral', '😐')], default='neutral', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('recommend', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_page.book')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_recommendations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
