# Generated by Django 4.2.6 on 2023-10-29 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_page', '0004_remove_komen_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekomendasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_buku', models.DecimalField(decimal_places=1, max_digits=5)),
                ('isi_rekomendasi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('genre_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_rekomendasi', to='book_page.book')),
                ('judul_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judul_rekomendasi', to='book_page.book')),
                ('suka_buku', models.ManyToManyField(blank=True, related_name='suka_rekomendasi', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rekomendasi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
