# Generated by Django 4.2.6 on 2023-10-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekomendasi',
            name='genre_buku',
            field=models.CharField(max_length=255),
        ),
    ]
