# Generated by Django 4.2.6 on 2023-10-29 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0002_alter_rekomendasi_genre_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekomendasi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
