# Generated by Django 4.2.6 on 2023-10-29 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0003_alter_rekomendasi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekomendasi',
            name='suka_buku',
        ),
        migrations.AddField(
            model_name='rekomendasi',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
