# Generated by Django 4.2.6 on 2023-10-29 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0005_remove_rekomendasi_liked_by_rekomendasi_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekomendasi',
            name='likes',
            field=models.ManyToManyField(related_name='rekomendasi_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
