# Generated by Django 4.2.6 on 2023-10-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buku', models.TextField(blank=True, null=True)),
                ('gambar_buku', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('jumlah_rating', models.TextField(blank=True, null=True)),
                ('genre_1', models.TextField(blank=True, null=True)),
                ('genre_2', models.TextField(blank=True, null=True)),
                ('genre_3', models.TextField(blank=True, null=True)),
                ('genre_4', models.TextField(blank=True, null=True)),
                ('genre_5', models.TextField(blank=True, null=True)),
                ('jumlah_halaman', models.IntegerField(blank=True, null=True)),
                ('waktu_publikasi', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
