# Generated by Django 4.2.6 on 2023-10-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_page', '0003_komen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komen',
            name='parent',
        ),
    ]
