# Generated by Django 4.2.4 on 2023-10-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_page', '0006_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='buku',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_page.book'),
        ),
        migrations.DeleteModel(
            name='Komen',
        ),
    ]
