# Generated by Django 4.2.4 on 2023-11-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_page', '0007_alter_bookmark_buku_delete_komen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='buku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_page.book'),
        ),
    ]
